services:
  checktruck.api:
    image: checktruck.api
    build:
      context: .
      dockerfile: CheckTruck.Api/Dockerfile

  db:
    image: postgres:14.23-trixie
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  
  adminer:
    image: adminer:standalone
    ports:
      - '8080:8080'