// <auto-generated />
using System;
using CheckTruck.Repositorio;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CheckTruck.Repositorio.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20261010022452_ContaFrotaOuAutonomo")]
    partial class ContaFrotaOuAutonomo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Chamado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AbertoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AbertoPorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("AtendidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AtendidoPorId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ConcluidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("EmpresaId")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Solucao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("Urgencia")
                        .HasColumnType("integer");

                    b.Property<long>("VeiculoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AbertoPorId");

                    b.HasIndex("AtendidoPorId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("Status");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Empresa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Documento")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("TipoConta")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Fabricante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("EmpresaId")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("PaisOrigemId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("PaisOrigemId");

                    b.ToTable("Fabricantes");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Geracao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("AnoFim")
                        .HasColumnType("integer");

                    b.Property<int>("AnoInicio")
                        .HasColumnType("integer");

                    b.Property<string>("Caixa")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("EmpresaId")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<long>("ModeloId")
                        .HasColumnType("bigint");

                    b.Property<string>("Motor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NormaEmissao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("ModeloId");

                    b.ToTable("Geracoes");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.IntervaloRecomendado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("EmpresaId")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Fonte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("GeracaoId")
                        .HasColumnType("bigint");

                    b.Property<int>("IntervaloKm")
                        .HasColumnType("integer");

                    b.Property<int>("IntervaloKmPrimeira")
                        .HasColumnType("integer");

                    b.Property<int>("IntervaloMeses")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TipoManutencaoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("GeracaoId");

                    b.HasIndex("TipoManutencaoId");

                    b.ToTable("IntervalosRecomendados");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.IntervaloVeiculo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EmpresaId")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int>("IntervaloKm")
                        .HasColumnType("integer");

                    b.Property<int>("IntervaloMeses")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<long>("TipoManutencaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("VeiculoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("TipoManutencaoId");

                    b.HasIndex("VeiculoId", "TipoManutencaoId")
                        .IsUnique();

                    b.ToTable("IntervalosVeiculo");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Manutencao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Concessionaria")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataProximaTroca")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EmpresaId")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPrimeiraTroca")
                        .HasColumnType("boolean");

                    b.Property<int>("KmAtual")
                        .HasColumnType("integer");

                    b.Property<int>("KmProximaTroca")
                        .HasColumnType("integer");

                    b.Property<string>("LancadoPorId")
                        .HasColumnType("text");

                    b.Property<long>("MecanicoId")
                        .HasColumnType("bigint");

                    b.Property<string>("MotoristaId")
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<DateTime>("RealizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TipoManutencaoId")
                        .HasColumnType("bigint");

                    b.Property<long>("VeiculoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("LancadoPorId");

                    b.HasIndex("MecanicoId");

                    b.HasIndex("MotoristaId");

                    b.HasIndex("TipoManutencaoId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Manutencoes");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Mecanico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<long>("EmpresaId")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Mecanicos");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Modelo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("EmpresaId")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<long>("FabricanteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("FabricanteId");

                    b.ToTable("Modelos");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Pais", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("EmpresaId")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Potencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Cv")
                        .HasColumnType("integer");

                    b.Property<long?>("EmpresaId")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<long>("GeracaoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("GeracaoId", "Cv")
                        .IsUnique();

                    b.ToTable("Potencias");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.RegistroKm", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EmpresaId")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int?>("KmAnterior")
                        .HasColumnType("integer");

                    b.Property<int>("KmNovo")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("OrdemServicoId")
                        .HasColumnType("bigint");

                    b.Property<int>("Origem")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegistradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegistradoPorId")
                        .HasColumnType("text");

                    b.Property<long>("VeiculoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("OrdemServicoId");

                    b.HasIndex("RegistradoPorId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("RegistrosKm");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.TipoManutencao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Componente")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("EmpresaId")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("TiposManutencao");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("Cargo")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<long?>("EmpresaId")
                        .HasColumnType("bigint");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<int>("Permissoes")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("EmpresaId", "Cpf")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Veiculo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AnoFabricacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("AnoModelo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<long>("EmpresaId")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<int>("KmAtual")
                        .HasColumnType("integer");

                    b.Property<string>("MotoristaAtualId")
                        .HasColumnType("text");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PotenciaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Renavam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tracao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MotoristaAtualId");

                    b.HasIndex("PotenciaId");

                    b.HasIndex("EmpresaId", "Chassi")
                        .IsUnique();

                    b.HasIndex("EmpresaId", "Placa")
                        .IsUnique();

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Chamado", b =>
                {
                    b.HasOne("CheckTruck.Dominio.Entidades.Usuario", "AbertoPor")
                        .WithMany()
                        .HasForeignKey("AbertoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CheckTruck.Dominio.Entidades.Usuario", "AtendidoPor")
                        .WithMany()
                        .HasForeignKey("AtendidoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CheckTruck.Dominio.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CheckTruck.Dominio.Entidades.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AbertoPor");

                    b.Navigation("AtendidoPor");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Fabricante", b =>
                {
                    b.HasOne("CheckTruck.Dominio.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CheckTruck.Dominio.Entidades.Pais", "PaisOrigem")
                        .WithMany("Fabricantes")
                        .HasForeignKey("PaisOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaisOrigem");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Geracao", b =>
                {
                    b.HasOne("CheckTruck.Dominio.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CheckTruck.Dominio.Entidades.Modelo", "Modelo")
                        .WithMany("Geracoes")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.IntervaloRecomendado", b =>
                {
                    b.HasOne("CheckTruck.Dominio.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CheckTruck.Dominio.Entidades.Geracao", "Geracao")
                        .WithMany("IntervalosRecomendados")
                        .HasForeignKey("GeracaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CheckTruck.Dominio.Entidades.TipoManutencao", "TipoManutencao")
                        .WithMany("IntervaloRecomendados")
                        .HasForeignKey("TipoManutencaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Geracao");

                    b.Navigation("TipoManutencao");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.IntervaloVeiculo", b =>
                {
                    b.HasOne("CheckTruck.Dominio.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CheckTruck.Dominio.Entidades.TipoManutencao", "TipoManutencao")
                        .WithMany()
                        .HasForeignKey("TipoManutencaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CheckTruck.Dominio.Entidades.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoManutencao");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Manutencao", b =>
                {
                    b.HasOne("CheckTruck.Dominio.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CheckTruck.Dominio.Entidades.Usuario", "LancadoPor")
                        .WithMany()
                        .HasForeignKey("LancadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CheckTruck.Dominio.Entidades.Mecanico", "Mecanico")
                        .WithMany()
                        .HasForeignKey("MecanicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CheckTruck.Dominio.Entidades.Usuario", "Motorista")
                        .WithMany()
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CheckTruck.Dominio.Entidades.TipoManutencao", "TipoManutencao")
                        .WithMany()
                        .HasForeignKey("TipoManutencaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CheckTruck.Dominio.Entidades.Veiculo", "Veiculo")
                        .WithMany("Manutencoes")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LancadoPor");

                    b.Navigation("Mecanico");

                    b.Navigation("Motorista");

                    b.Navigation("TipoManutencao");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Mecanico", b =>
                {
                    b.HasOne("CheckTruck.Dominio.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Modelo", b =>
                {
                    b.HasOne("CheckTruck.Dominio.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CheckTruck.Dominio.Entidades.Fabricante", "Fabricante")
                        .WithMany("Modelos")
                        .HasForeignKey("FabricanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fabricante");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Pais", b =>
                {
                    b.HasOne("CheckTruck.Dominio.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Potencia", b =>
                {
                    b.HasOne("CheckTruck.Dominio.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CheckTruck.Dominio.Entidades.Geracao", "Geracao")
                        .WithMany("Potencias")
                        .HasForeignKey("GeracaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Geracao");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.RegistroKm", b =>
                {
                    b.HasOne("CheckTruck.Dominio.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CheckTruck.Dominio.Entidades.Manutencao", "OrdemServico")
                        .WithMany()
                        .HasForeignKey("OrdemServicoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CheckTruck.Dominio.Entidades.Usuario", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CheckTruck.Dominio.Entidades.Veiculo", "Veiculo")
                        .WithMany("RegistrosKm")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdemServico");

                    b.Navigation("RegistradoPor");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.TipoManutencao", b =>
                {
                    b.HasOne("CheckTruck.Dominio.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Usuario", b =>
                {
                    b.HasOne("CheckTruck.Dominio.Entidades.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Veiculo", b =>
                {
                    b.HasOne("CheckTruck.Dominio.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CheckTruck.Dominio.Entidades.Usuario", "MotoristaAtual")
                        .WithMany()
                        .HasForeignKey("MotoristaAtualId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CheckTruck.Dominio.Entidades.Potencia", "Potencia")
                        .WithMany("Veiculos")
                        .HasForeignKey("PotenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MotoristaAtual");

                    b.Navigation("Potencia");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CheckTruck.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CheckTruck.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CheckTruck.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Fabricante", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Geracao", b =>
                {
                    b.Navigation("IntervalosRecomendados");

                    b.Navigation("Potencias");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Modelo", b =>
                {
                    b.Navigation("Geracoes");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Pais", b =>
                {
                    b.Navigation("Fabricantes");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Potencia", b =>
                {
                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.TipoManutencao", b =>
                {
                    b.Navigation("IntervaloRecomendados");
                });

            modelBuilder.Entity("CheckTruck.Dominio.Entidades.Veiculo", b =>
                {
                    b.Navigation("Manutencoes");

                    b.Navigation("RegistrosKm");
                });
#pragma warning restore 612, 618
        }
    }
}
